services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: "FROM postgres:17-alpine"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
