services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./app/src:/app/src
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_PROFILES_ACTIVE=dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./build.gradle
          target: /app/build.gradle
        - action: rebuild
          path: ./settings.gradle
          target: /app/settings.gradle

  postgres:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
