services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - app/.gradle
            - app/build
        - action: rebuild
          path: Dockerfile
  postgres:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
