version: "3.8"

services:
  app:
    build:
      context: ../../app
      dockerfile: ../docker/prod/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx1g
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=tonapp
      - POSTGRES_USER=produser
      - POSTGRES_PASSWORD=prodpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
